### PR TITLE
Fix callback issue when task done

### LINKED ISSUE #581: Failed to run demo job
**Describe the bug**
Failed to run demo job. We can reproduce the issue by following steps:
  **step 1** Install and start the console by the [Quick Start](https://github.com/apache/geaflow?tab=readme-ov-file#quick-start).
  **step 2**  Run the demo job.
Image
  **step 3** We can see that the task status is failed.
Image

**Expected behavior**
Suuccess to run demo job

**Additional context**
Some error messages were found in file `/tmp/logs/task/geaflow1754646605984791446.log` that may be related to the issue.

Image

### PR DESCRIPTION
**Pull request by chzhoo**
### What changes were proposed in this pull request?

1. In [PR 531](https://github.com/apache/geaflow/pull/531), a callback mechanism upon task completion was introduced.
2. The callback request is implemented via a POST method, but an invalid body format in the POST request caused [ISSUE 581](https://github.com/apache/geaflow/issues/581).
3. This PR fixes the issue of invalid request body.
    3.1 POST body before changes: `{"success":true,"data":{"params":{"action":"finish"}}}`
    3.2 POST body after changes: `{"success":true,"action":"finish"}`

### How was this PR tested?

- [x] Tests have Added for the changes
- [x] Production environment verified

Closes #581

### CODE REVIEW

File: geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/org/apache/geaflow/cluster/client/callback/RestJobOperatorCallback.java [hunk 1]
```diff
@@ -52,16 +51,13 @@ public RestJobOperatorCallback(Configuration config, String url) {
...
+        jobOperatorMeta.setSuccess(true);
+        jobOperatorMeta.setAction(FINISH_ACTION_KEY);
 
         String fullUrl = getFullUrl(jobOperatorMeta);
         if (fullUrl != null) {
-            HttpRequest request = new HttpRequest();
-            request.setSuccess(true);
-            request.setData(jobOperatorMeta);
-            HttpUtil.post(fullUrl, new Gson().toJson(request), headers);
+            HttpUtil.post(fullUrl, new Gson().toJson(jobOperatorMeta), headers);
```
Comment (xincai98) [inline geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/org/apache/geaflow/cluster/client/callback/RestJobOperatorCallback.java:60]: Before send request, please print fullUrl and jobOperatorMeta's json result to log for  troubleshooting problems

Comment (chzhoo) [reply geaflow/geaflow-core/geaflow-engine/geaflow-cluster/src/main/java/org/apache/geaflow/cluster/client/callback/RestJobOperatorCallback.java:60]: Thanks for your reply. The fullUrl and jobOperatorMeta's json result are already logged inside the `HttpUtil.post` method
image

**Review by xincai98 — APPROVED** [review]
